# Use the official Node.js Alpine image as the base image
FROM bitnami/node:20.11.1-debian-12-r2
# FROM  ubuntu:22.04

# Set the working directory inside the container
WORKDIR /app/project

# Copy package.json and package-lock.json to the working directory
COPY package*.json .
# COPY ./.next ./.next

COPY . .


     
RUN ls && \
    chmod -R 777 ./ && \
    echo "deb https://ftp.halifax.rwth-aachen.de/debian bookworm main" >> /etc/apt/temp.list && \
    echo "deb https://ftp.halifax.rwth-aachen.de/debian bookworm-updates main " >> /etc/apt/temp.list && \
    cat /etc/apt/temp.list /etc/apt/sources.list > /etc/apt/sources.list.new && mv /etc/apt/sources.list.new /etc/apt/sources.list && \
      apt update -y && \
      apt install curl git procps sudo -y && \  
      node -v && \ 
      npm -v && \ 
      npm i && \
      find . -name ".env" -type f -exec rm {} + 

CMD ["npm", "start"]

EXPOSE 3000




