import Head from "next/head";

import { Inter } from "next/font/google";

import { Button } from "@/components/button/button";
import { Input } from "@/components/input/input";
import { Select } from "@/components/select/select";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className}`}>
        <div>hello</div>
        <Button title="Click me" backgroundColor="red" />
        <div
          style={{
            width: "20%",
          }}
        >
          <Input />
        </div>

        <div
          style={{
            width: "20%",
          }}
        >
          <Select />
        </div>
      </main>
    </>
  );
}
